<html>
<head>
    <meta charset="UTF-8"/>
    <title>顯示單一班級資料</title>
</head>
<body>
<h1>顯示單一班級資料</h1>
<table border="1">
    <tr>
        <th>編號</th>
        <td>{{$Class->id}}</td>
    </tr>
    <tr>
        <th>系別</th>
        <td>{{$Class->department}}</td>
    </tr>
    <tr>
        <th>班級名稱</th>
        <td>{{$Class->classname}}</td>
    </tr>
    <tr>
        <th>年級</th>
        <td>{{$Class->grade}}</td>
    </tr>
    <tr>
        <th>教室</th>
        <td>{{$Class->classroom}}</td>
    </tr>
    <tr>
        <th>班導</th>
        <td>{{$Class->teacher}}</td>
    </tr>
</table>
</body>
</html>
