<html>
<head>
    <meta charset="UTF-8"/>
    <title>顯示單一班級資料</title>
</head>
<body>
<h1>顯示單一班級資料</h1>
<table border="1">
    <tr>
        <th>編號</th>
        <td>{{$Class->id}}</td>
    </tr>
    <tr>
        <th>系別</th>
        <td>{{$Class->department}}</td>
    </tr>
    <tr>
        <th>班級名稱</th>
        <td>{{$Class->classname}}</td>
    </tr>
    <tr>
        <th>年級</th>
        <td>{{$Class->grade}}</td>
    </tr>
    <tr>
        <th>教室</th>
        <td>{{$Class->classroom}}</td>
    </tr>
    <tr>
        <th>班導</th>
        <td>{{$Class->teacher}}</td>
    </tr>
</table>
<h1>班級所有學生資料</h1>
<table border="1">
    <tr>
        <th>編號</th>
        <th>學號</th>
        <th>座號</th>
        <th>姓名</th>
        <th>性別</th>
        <th>班級</th>
        <th>畢業年份</th>
        <th>入學年份</th>
        <th>座位</th>
        <th>出生地</th>
    </tr>
    @foreach($Class->Student as $Student)
    <tr>
        <td>{{$Student->id}}</td>
        <td>{{$Student->student_id}}</td>
        <td>{{$Student->seat_number}}</td>
        <td>{{$Student->name}}</td>
        <td>{{$Student->gender}}</td>
        <td>{{$Student->cid}}</td>
        <td>{{$Student->graduation_year}}</td>
        <td>{{$Student->start_year}}</td>
        <td>{{$Student->seat}}</td>
        <td>{{$Student->country}}</td>
    </tr>
    @endforeach
</table>
</body>
</html>
